* meta
** startups
//		#+STARTUP: hidestars	
#+SEQ_TODO: TODO(t!) START(s!) STUCK(k!) WAIT(w!) | DONE(d!) CANCEL(c!) DEFER(r!) ANSWER(n!)
#+PROPERTY: imp_ALL high medium low
#+PROPERTY: urg_ALL immediate shortterm longterm
#+PROPERTY: loc_ALL home office
#+COLUMNS: %imp %urg %loc
* Creating a Docker Swarm Cluster
** Introduction
 [Swarm mode]() is the orchestration feature built into Docker. It's a production-grade orchestrator which uses the familiar Docker Compose format to model applications.

 We'll create a Swarm cluster for this section and deploy some apps to get a feel for running containers in production. 

 If you plan on using a different orchestrator - like Kubernetes or Nomad - the patterns are the same, so what you learn here will still apply.
*** vagrant
 DockerForWindows and LearnDockerInAMonth both cover Docker Swarm but not using Vagrant.

https://www.vagrantup.com/downloads
downloaded Vagrant 2.2.16 64bit 
** Pre-reqs

We'll run multiple virtual machines to create a production-like cluster, so you'll need to install [[https://www.vagrantup.com/][Vagrant]] if you want to follow along.

The [Vagrantfile]() sets up four machines with Docker installed and ready to be joined into a cluster.

_Use Vagrant to create 3x Linux and 1x Windows VMs:_
$env:docker4dotnet='c:\cprojects\udemy\docker4.net'

```
cd "$env:docker4dotnet/vagrant/05"

vagrant up
```
*** problem with 'vagrant up'
**** trancript on //air
 PS C:\cprojects\udemy\docker4.net\vagrant\05> vagrant up
 Bringing machine 'manager' up with 'virtualbox' provider...
 Bringing machine 'worker' up with 'virtualbox' provider...
 Bringing machine 'worker2' up with 'virtualbox' provider...
 Bringing machine 'winworker' up with 'virtualbox' provider...
 ==> manager: Box 'bento/ubuntu-20.04' could not be found. Attempting to find and install...
     manager: Box Provider: virtualbox
     manager: Box Version: >= 0
 ==> manager: Loading metadata for box 'bento/ubuntu-20.04'
     manager: URL: https://vagrantcloud.com/bento/ubuntu-20.04
 ==> manager: Adding box 'bento/ubuntu-20.04' (v202105.25.0) for provider: virtualbox
     manager: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-20.04/versions/202105.25.0/providers/virtualbox.box
     manager:
 ==> manager: Successfully added box 'bento/ubuntu-20.04' (v202105.25.0) for 'virtualbox'!
 ==> manager: Importing base box 'bento/ubuntu-20.04'...
 ==> manager: Matching MAC address for NAT networking...
 ==> manager: Checking if box 'bento/ubuntu-20.04' version '202105.25.0' is up to date...
 ==> manager: Setting the name of the VM: manager
 Vagrant is currently configured to create VirtualBox synced folders with
 the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
 guest is not trusted, you may want to disable this option. For more
 information on this option, please refer to the VirtualBox manual:

   https://www.virtualbox.org/manual/ch04.html#sharedfolders

 This option can be disabled globally with an environment variable:

   VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

 or on a per folder basis within the Vagrantfile:

   config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false
 ==> manager: Vagrant has detected a configuration issue which exposes a
 ==> manager: vulnerability with the installed version of VirtualBox. The
 ==> manager: current guest is configured to use an E1000 NIC type for a
 ==> manager: network adapter which is vulnerable in this version of VirtualBox.
 ==> manager: Ensure the guest is trusted to use this configuration or update
 ==> manager: the NIC type using one of the methods below:
 ==> manager:
 ==> manager:   https://www.vagrantup.com/docs/virtualbox/configuration.html#default-nic-type
 ==> manager:   https://www.vagrantup.com/docs/virtualbox/networking.html#virtualbox-nic-type
 ==> manager: Clearing any previously set network interfaces...
 ==> manager: Preparing network interfaces based on configuration...
     manager: Adapter 1: nat
     manager: Adapter 2: hostonly
 ==> manager: Forwarding ports...
     manager: 22 (guest) => 2222 (host) (adapter 1)
 ==> manager: Running 'pre-boot' VM customizations...
 ==> manager: Booting VM...
 There was an error while executing `VBoxManage`, a CLI used by Vagrant
 for controlling VirtualBox. The command and stderr is shown below.

 Command: ["startvm", "24a2dc14-fa89-47eb-9381-847f7b25b513", "--type", "headless"]

 Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
 VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
**** uninstall virtualbox 5.2, installed vb 6.1
**** transcript on //air, same error even if running powershell as admin
 PS C:\cprojects\udemy\docker4.net\vagrant\05> vagrant up
 Bringing machine 'manager' up with 'virtualbox' provider...
 Bringing machine 'worker' up with 'virtualbox' provider...
 Bringing machine 'worker2' up with 'virtualbox' provider...
 Bringing machine 'winworker' up with 'virtualbox' provider...
 ==> manager: Checking if box 'bento/ubuntu-20.04' version '202105.25.0' is up to date...
 ==> manager: Clearing any previously set forwarded ports...
 ==> manager: Clearing any previously set network interfaces...
 ==> manager: Preparing network interfaces based on configuration...
     manager: Adapter 1: nat
     manager: Adapter 2: hostonly
 ==> manager: Forwarding ports...
     manager: 22 (guest) => 2222 (host) (adapter 1)
 ==> manager: Running 'pre-boot' VM customizations...
 ==> manager: Booting VM...
 There was an error while executing `VBoxManage`, a CLI used by Vagrant
 for controlling VirtualBox. The command and stderr is shown below.

 Command: ["startvm", "24a2dc14-fa89-47eb-9381-847f7b25b513", "--type", "headless"]

 Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
 VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
 VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
**** the diff is that for vb 6.1, VB can invoke on Win10
 https://www.tcg.com/blog/yes-you-can-run-docker-and-virtualbox-on-windows-10-home/
**** DONE S5L2 Problem with "vagrant up"
     CLOSED: [2021-06-18 Fri 10:56]
     - State "DONE"       from "START"      [2021-06-18 Fri 10:56]
     - State "START"      from              [2021-06-07 Mon 10:53]
***** problem description
  I have been able to run all the examples as I follow the videos in Sections 1 to 4.
  In Section 5, Lecture 2, when I run "vagrant up" in the 05 folder, I get an error.

     > PS C:\cprojects\udemy\docker4.net\vagrant\05> vagrant up
     > Bringing machine 'manager' up with 'virtualbox' provider...
     > Bringing machine 'worker' up with 'virtualbox' provider...
     > Bringing machine 'worker2' up with 'virtualbox' provider...
     > Bringing machine 'winworker' up with 'virtualbox' provider...
     > ==> manager: Checking if box 'bento/ubuntu-20.04' version '202105.25.0' is up to date...
     > ==> manager: Clearing any previously set forwarded ports...
     > ==> manager: Clearing any previously set network interfaces...
     > ==> manager: Preparing network interfaces based on configuration...
     >     manager: Adapter 1: nat
     >     manager: Adapter 2: hostonly
     > ==> manager: Forwarding ports...
     >     manager: 22 (guest) => 2222 (host) (adapter 1)
     > ==> manager: Running 'pre-boot' VM customizations...
     > ==> manager: Booting VM...
     > There was an error while executing `VBoxManage`, a CLI used by Vagrant
     > for controlling VirtualBox. The command and stderr is shown below.
     > 
     > Command: ["startvm", "24a2dc14-fa89-47eb-9381-847f7b25b513", "--type", "headless"]
     > 
     > Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
     > VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
     > VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
     > 
  If anyone knows what the problem is, thanks for your help in advance.

***** environment
 Windows 10 2004 with WSL2
 Vagrant 2.2.16
 VirtualBox 6.1

 I do not believe the problem has anything to do with docker but just in case, here are the versions
 c:\cprojects\pp\virtualization\docker>docker version
 docker version
 Client:
  Cloud integration: 1.0.14
  Version:           20.10.6
  API version:       1.41
  Go version:        go1.16.3
  Git commit:        370c289
  Built:             Fri Apr  9 22:49:36 2021
  OS/Arch:           windows/amd64
  Context:           default
  Experimental:      true

 Server: Docker Engine - Community
  Engine:
   Version:          20.10.6
   API version:      1.41 (minimum version 1.24)
   Go version:       go1.13.15
   Git commit:       8728dd2
   Built:            Fri Apr  9 22:45:40 2021
   OS/Arch:          windows/amd64
   Experimental:     false

 Docker Desktop V 3.3.3(64133)

***** fix1: Upgrade virtualbox from 5.2 to 6.1
This elimiated the error about : Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
However, there is now another issue.
As the transcript below shows, vagrant times out waiting for the machine to boot.

***** c:\cprojects\udemy\docker4.net\vagrant\05>vagrant up
Bringing machine 'manager' up with 'virtualbox' provider...
Bringing machine 'worker' up with 'virtualbox' provider...
Bringing machine 'worker2' up with 'virtualbox' provider...
Bringing machine 'winworker' up with 'virtualbox' provider...
==> manager: Checking if box 'bento/ubuntu-20.04' version '202105.25.0' is up to date...
==> manager: Clearing any previously set forwarded ports...
==> manager: Clearing any previously set network interfaces...
==> manager: Preparing network interfaces based on configuration...
    manager: Adapter 1: nat
    manager: Adapter 2: hostonly
==> manager: Forwarding ports...
    manager: 22 (guest) => 2222 (host) (adapter 1)
==> manager: Running 'pre-boot' VM customizations...
==> manager: Booting VM...
==> manager: Waiting for machine to boot. This may take a few minutes...
    manager: SSH address: 127.0.0.1:2222
    manager: SSH username: vagrant
    manager: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
***** I am writing this to close the ticket. The cause is a comedy of errors that I will explain later.
Summary: 
Based on this url, https://computingforgeeks.com/enable-hyper-v-and-install-vagrant-in-windows/
I uninstalled VirtualBox, and turned on my Hyper-V settings. 

Then, the simple "getting started" instructions ( https://learn.hashicorp.com/tutorials/vagrant/getting-started-index?in=vagrant/getting-started )
now work, ie 
   vagrant box add hashicorp/bionic64 // select hyperv provider when prompted
   vagrant up
   vagrant ssh  

Comedy of errors:
  1. I had been using VirtualBox before Docker, and had disabled it while Docker was active.
  2. Vagrant works with several providers like VirtualBox and HyperV, so it assumed that I wanted to use VirtualBox
  3. That led me to upgrade my VirtualBox from 5.2 to 6.1 but there were still issues.
  4. The class video I viewed showed that Elton's "vagrant status" was running in HyperV, not VirtualBox, giving 
     me the clue to uninstall VirtualBox and try again. 
**** START S5L2 winworker - windows version incompatible
     - State "START"      from              [2021-06-18 Fri 10:56]
I am on Section 5, Lesson 2 and trying to run vagrant with hyperv, on Windows 10.

The "vagrant up" runs but has the following message at the end of the run:

>    winworker: Status: Downloaded newer image for docker4dotnet/homepage:05-03
>    winworker: docker.io/docker4dotnet/homepage:05-03
>    winworker: 05-03: Pulling from docker4dotnet/save-handler
>    winworker: a Windows version 10.0.19042-based image is incompatible with a 10.0.17763 host

I understand that for "hyper-v", the windows image version must exactly match. This is a bad situation, 
because Windows 10 tries to update my PC regularly. In fact my 10.0.19042 update happened just a few
days ago.

Instead of providing another image for a specific windows version ( moving target ), it might be more
useful to show how a user can update the Dockerfile to get the correct version of windows image and
the changes needed in the Vagrantfile to get this lecture example working again. Just a suggestion.

Thanks and hope I hear from someone soon. 

*** simple vagrant startup
**** c:\tmp>vagrant init hashicorp/bionic64
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
**** c:\tmp>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hashicorp/bionic64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'hashicorp/bionic64'
    default: URL: https://vagrantcloud.com/hashicorp/bionic64
==> default: Adding box 'hashicorp/bionic64' (v1.0.282) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/hashicorp/boxes/bionic64/versions/1.0.282/providers/virtualbox.box
    default:
==> default: Successfully added box 'hashicorp/bionic64' (v1.0.282) for 'virtualbox'!
==> default: Importing base box 'hashicorp/bionic64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'hashicorp/bionic64' version '1.0.282' is up to date...
==> default: Setting the name of the VM: tmp_default_1623109119626_69301
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
*** kwee1 transcript that works
Microsoft Windows [Version 10.0.19041.1052]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>cd c:\tmp

c:\tmp>ls
Vagrantfile  announce.txt  announce1.txt  init.el  ubuntu-installed.org

c:\tmp>vagrant status
Current machine states:

default                   poweroff (virtualbox)

The VM is powered off. To restart the VM, simply run `vagrant up`

c:\tmp>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'hashicorp/bionic64' version '1.0.282' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 6.0.10
    default: VirtualBox Version: 6.1
==> default: Mounting shared folders...
    default: /vagrant => C:/tmp
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

c:\tmp>vagrant --debug ssh
 INFO global: Vagrant version: 2.2.16
 INFO global: Ruby version: 2.6.7
 INFO global: RubyGems version: 3.0.3.1
 INFO global: VAGRANT_EXECUTABLE="C:\\HashiCorp\\Vagrant\\embedded\\gems\\2.2.16\\gems\\vagrant-2.2.16\\bin\\vagrant"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="C:\\HashiCorp\\Vagrant\\embedded"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_LOG="debug"
 WARN global: resolv replacement has not been enabled!
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/autocomplete/plugin.rb
 INFO manager: Registered plugin: autocomplete command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/box/plugin.rb
 INFO manager: Registered plugin: box command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cap/plugin.rb
 INFO manager: Registered plugin: cap command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/plugin.rb
 INFO manager: Registered plugin: vagrant-cloud
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/destroy/plugin.rb
 INFO manager: Registered plugin: destroy command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/global-status/plugin.rb
 INFO manager: Registered plugin: global-status command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/halt/plugin.rb
 INFO manager: Registered plugin: halt command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/help/plugin.rb
 INFO manager: Registered plugin: help command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/init/plugin.rb
 INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/list-commands/plugin.rb
 INFO manager: Registered plugin: list-commands command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/login/plugin.rb
 INFO manager: Registered plugin: vagrant-login
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/package/plugin.rb
 INFO manager: Registered plugin: package command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/plugin.rb
 INFO manager: Registered plugin: plugin command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/port/plugin.rb
 INFO manager: Registered plugin: port command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/powershell/plugin.rb
 INFO manager: Registered plugin: powershell command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/provider/plugin.rb
 INFO manager: Registered plugin: provider command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/provision/plugin.rb
 INFO manager: Registered plugin: provision command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/push/plugin.rb
 INFO manager: Registered plugin: push command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/rdp/plugin.rb
 INFO manager: Registered plugin: rdp command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/reload/plugin.rb
 INFO manager: Registered plugin: reload command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/resume/plugin.rb
 INFO manager: Registered plugin: resume command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/snapshot/plugin.rb
 INFO manager: Registered plugin: snapshot command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/ssh/plugin.rb
 INFO manager: Registered plugin: ssh command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/ssh_config/plugin.rb
 INFO manager: Registered plugin: ssh-config command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/status/plugin.rb
 INFO manager: Registered plugin: status command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/suspend/plugin.rb
 INFO manager: Registered plugin: suspend command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/up/plugin.rb
 INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/upload/plugin.rb
 INFO manager: Registered plugin: upload command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/validate/plugin.rb
 INFO manager: Registered plugin: validate command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/version/plugin.rb
 INFO manager: Registered plugin: version command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/winrm/plugin.rb
 INFO manager: Registered plugin: winrm command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/winrm_config/plugin.rb
 INFO manager: Registered plugin: winrm-config command
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/communicators/winrm/plugin.rb
 INFO manager: Registered plugin: winrm communicator
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/communicators/winssh/plugin.rb
 INFO manager: Registered plugin: windows ssh communicator
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/alpine/plugin.rb
 INFO manager: Registered plugin: Alpine guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/alt/plugin.rb
 INFO manager: Registered plugin: ALT Platform guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/amazon/plugin.rb
 INFO manager: Registered plugin: Amazon Linux guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/arch/plugin.rb
 INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/atomic/plugin.rb
 INFO manager: Registered plugin: Atomic Host guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/bsd/plugin.rb
 INFO manager: Registered plugin: BSD-based guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/centos/plugin.rb
 INFO manager: Registered plugin: CentOS guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/coreos/plugin.rb
 INFO manager: Registered plugin: CoreOS guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/darwin/plugin.rb
 INFO manager: Registered plugin: Darwin guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/debian/plugin.rb
 INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/dragonflybsd/plugin.rb
 INFO manager: Registered plugin: DragonFly BSD guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/elementary/plugin.rb
 INFO manager: Registered plugin: Elementary guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/esxi/plugin.rb
 INFO manager: Registered plugin: ESXi guest.
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/funtoo/plugin.rb
 INFO manager: Registered plugin: Funtoo guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/haiku/plugin.rb
 INFO manager: Registered plugin: Haiku guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/kali/plugin.rb
 INFO manager: Registered plugin: Kali guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/linux/plugin.rb
 INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/mint/plugin.rb
 INFO manager: Registered plugin: Mint guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/netbsd/plugin.rb
 INFO manager: Registered plugin: NetBSD guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/nixos/plugin.rb
 INFO manager: Registered plugin: NixOS guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/omnios/plugin.rb
 INFO manager: Registered plugin: OmniOS guest.
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/openbsd/plugin.rb
 INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/openwrt/plugin.rb
 INFO manager: Registered plugin: OpenWrt guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/photon/plugin.rb
 INFO manager: Registered plugin: VMware Photon guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/pld/plugin.rb
 INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/smartos/plugin.rb
 INFO manager: Registered plugin: SmartOS guest.
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/solaris/plugin.rb
 INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/solaris11/plugin.rb
 INFO manager: Registered plugin: Solaris 11 guest.
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/suse/plugin.rb
 INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/tinycore/plugin.rb
 INFO manager: Registered plugin: TinyCore Linux guest.
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/trisquel/plugin.rb
 INFO manager: Registered plugin: Trisquel guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/ubuntu/plugin.rb
 INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/guests/windows/plugin.rb
 INFO manager: Registered plugin: Windows guest.
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/alt/plugin.rb
 INFO manager: Registered plugin: ALT Platform host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/arch/plugin.rb
 INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/bsd/plugin.rb
 INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/darwin/plugin.rb
 INFO manager: Registered plugin: Mac OS X host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/linux/plugin.rb
 INFO manager: Registered plugin: Linux host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/null/plugin.rb
 INFO manager: Registered plugin: null host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/suse/plugin.rb
 INFO manager: Registered plugin: SUSE host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/void/plugin.rb
 INFO manager: Registered plugin: Void host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/hosts/windows/plugin.rb
 INFO manager: Registered plugin: Windows host
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/kernel_v1/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/kernel_v2/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/docker/plugin.rb
 INFO manager: Registered plugin: docker-provider
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/hyperv/plugin.rb
 INFO manager: Registered plugin: Hyper-V provider
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/plugin.rb
 INFO manager: Registered plugin: VirtualBox provider
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/provisioners/ansible/plugin.rb
 INFO manager: Registered plugin: ansible
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/provisioners/cfengine/plugin.rb
 INFO manager: Registered plugin: CFEngine Provisioner
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/provisioners/chef/plugin.rb
 INFO manager: Registered plugin: chef
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/provisioners/container/plugin.rb
 INFO manager: Registered plugin: container
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/provisioners/docker/plugin.rb
 INFO manager: Registered plugin: docker
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/provisioners/file/plugin.rb
 INFO manager: Registered plugin: file
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/provisioners/podman/plugin.rb
 INFO manager: Registered plugin: podman
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/provisioners/puppet/plugin.rb
 INFO manager: Registered plugin: puppet
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/provisioners/salt/plugin.rb
 INFO manager: Registered plugin: salt
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/provisioners/shell/plugin.rb
 INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/pushes/atlas/plugin.rb
 INFO manager: Registered plugin: atlas
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/pushes/ftp/plugin.rb
 INFO manager: Registered plugin: ftp
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/pushes/heroku/plugin.rb
 INFO manager: Registered plugin: heroku
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/pushes/local-exec/plugin.rb
 INFO manager: Registered plugin: local-exec
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/pushes/noop/plugin.rb
 INFO manager: Registered plugin: noop
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/synced_folders/nfs/plugin.rb
 INFO manager: Registered plugin: NFS synced folders
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/synced_folders/rsync/plugin.rb
 INFO manager: Registered plugin: RSync synced folders
DEBUG global: Loading core plugin: C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/synced_folders/smb/plugin.rb
 INFO manager: Registered plugin: SMB synced folders
 INFO vagrant: `vagrant` invoked: ["--debug", "ssh"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#<Vagrant::Environment:0x0000026aacb35fb0>)
 INFO environment:   - cwd: c:/tmp
 INFO environment: Home path: C:/Users/tankh/.vagrant.d
DEBUG environment: Effective local data path: c:/tmp/.vagrant
 INFO environment: Local data path: c:/tmp/.vagrant
DEBUG environment: Creating: c:/tmp/.vagrant
DEBUG manager: Enabling localized plugins
 INFO manager: Plugins:
DEBUG solution_file: new solution file instance plugin_file=c:/tmp/.vagrant/plugins.json solution_file=c:/tmp/.vagrant/bundler/local.sol
DEBUG solution_file: missing file so skipping loading
DEBUG bundler: solution file in use for init: <Vagrant::Bundler::SolutionFile:c:/tmp/.vagrant/plugins.json:c:/tmp/.vagrant/bundler/local.sol:invalid>
DEBUG bundler: Generating new builtin set instance.
DEBUG bundler: Generating new plugin set instance. Skip gems - []
DEBUG bundler: generating solution set for configured plugins
DEBUG bundler: Current generated plugin dependency list: []
DEBUG bundler: resolving solution from available specification set
DEBUG bundler: solution set for configured plugins has been resolved
DEBUG bundler: activating solution set
DEBUG bundler: Activating solution set: []
DEBUG solution_file: plugin file does not exist, not storing solution
DEBUG bundler: solution set stored to - <Vagrant::Bundler::SolutionFile:c:/tmp/.vagrant/plugins.json:c:/tmp/.vagrant/bundler/local.sol:invalid>
 INFO manager: Loading plugins...
DEBUG manager: Enabling globalized plugins
 INFO manager: Plugins:
DEBUG solution_file: new solution file instance plugin_file=C:/Users/tankh/.vagrant.d/plugins.json solution_file=c:/tmp/.vagrant/bundler/global.sol
DEBUG solution_file: missing file so skipping loading
DEBUG bundler: solution file in use for init: <Vagrant::Bundler::SolutionFile:C:/Users/tankh/.vagrant.d/plugins.json:c:/tmp/.vagrant/bundler/global.sol:invalid>
DEBUG bundler: Generating new builtin set instance.
DEBUG bundler: Generating new plugin set instance. Skip gems - []
DEBUG bundler: generating solution set for configured plugins
DEBUG bundler: Current generated plugin dependency list: []
DEBUG bundler: resolving solution from available specification set
DEBUG bundler: solution set for configured plugins has been resolved
DEBUG bundler: activating solution set
DEBUG bundler: Activating solution set: []
DEBUG solution_file: plugin file does not exist, not storing solution
DEBUG bundler: solution set stored to - <Vagrant::Bundler::SolutionFile:C:/Users/tankh/.vagrant.d/plugins.json:c:/tmp/.vagrant/bundler/global.sol:invalid>
 INFO manager: Loading plugins...
 INFO loader: Set :root = ["#<Pathname:c:/tmp/Vagrantfile>"]
DEBUG loader: Populating proc cache for #<Pathname:c:/tmp/Vagrantfile>
DEBUG loader: Load procs for pathname: c:/tmp/Vagrantfile
 INFO loader: Loading configuration in order: [:home, :root]
DEBUG loader: Loading from: root (evaluating)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "Write-Output $PSVersionTable.PSVersion.Major"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 5
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 29
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "(new-object System.Security.Principal.WindowsPrincipal([System.Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: False
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31998
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "Write-Output ([System.Security.Principal.WindowsIdentity]::GetCurrent().Groups | Select-Object Value | ConvertTo-JSON)"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: [
    {
        "Value":  "S-1-5-21-3841494138-2193452205-721468458-513"
    },
    {
        "Value":  "S-1-1-0"
    },
    {
        "Value":  "S-1-5-21-3841494138-2193452205-721468458-1004"
    },
    {
        "Value":  "S-1-5-32-559"
    },
    {
        "Value":  "S-1-5-32-545"
    },
    {
        "Value":  "S-1-5-14"
    },
    {
        "Value":  "S-1-5-4"
    },
    {
        "Value":  "S-1-5-11"
    },
    {
        "Value":  "S-1-5-15"
    },
    {
        "Value":  "S-1-5-113"
    },
    {
        "Value":  "S-1-2-0"
    },
    {
        "Value":  "S-1-5-64-10"
    }
]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "$x = (Get-VMHost).Name; if($x -eq [System.Net.Dns]::GetHostName()){ Write-Output 'true'}"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: Get-VMHost : You do not have the required permission to complete this task. Contact the administrator of the
authorization policy for the computer 'KWEE1'.
At line:1 char:7
+ $x = (Get-VMHost).Name; if($x -eq [System.Net.Dns]::GetHostName()){ W ...
+       ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-VMHost], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.GetVMHost

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31998
DEBUG subprocess: Exit status: 0
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "--version"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 6.1.22r144080
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG meta: Finding driver for VirtualBox version: 6.1.22
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_6_1
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
DEBUG environment: Initial usable provider list: [[6, :virtualbox]]
DEBUG environment: Priority sorted usable provider list: [:virtualbox]
DEBUG environment: Preferred provider list: []
DEBUG environment: Using provider `virtualbox` as it is the highest priority in the usable list.
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
DEBUG meta: Finding driver for VirtualBox version: 6.1.22
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_6_1
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
DEBUG environment: Initial usable provider list: [[6, :virtualbox]]
DEBUG environment: Priority sorted usable provider list: [:virtualbox]
DEBUG environment: Preferred provider list: []
DEBUG environment: Using provider `virtualbox` as it is the highest priority in the usable list.
 INFO loader: Set "1328592901400_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "1328592901400_machine_default"]
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO box_collection: Box found: hashicorp/bionic64 (virtualbox)
 INFO environment: Running hook: authenticate_box_url
 INFO host: Autodetecting host type for [#<Vagrant::Environment: c:/tmp>]
DEBUG host: Trying: alt
DEBUG host: Trying: arch
DEBUG host: Trying: darwin
DEBUG host: Trying: freebsd
DEBUG host: Trying: gentoo
DEBUG host: Trying: redhat
DEBUG host: Trying: slackware
DEBUG host: Trying: suse
DEBUG host: Trying: void
DEBUG host: Trying: bsd
DEBUG host: Trying: linux
DEBUG host: Trying: null
DEBUG host: Trying: windows
 INFO host: Detected: windows!
 INFO runner: Running action: authenticate_box_url #<Vagrant::Action::Builder:0x0000026aacc0a058>
 INFO warden: Calling IN action: #<VagrantPlugins::CloudCommand::AddAuthentication:0x0000026aaca5bb30>
 WARN authenticate-box-url: Removing access token from URL parameter.
 WARN authenticate-box-url: Authentication token not added as GET parameter.
 INFO warden: Calling OUT action: #<VagrantPlugins::CloudCommand::AddAuthentication:0x0000026aaca5bb30>
 INFO loader: Set :"1328588462240_hashicorp/bionic64_virtualbox" = ["#<Pathname:C:/Users/tankh/.vagrant.d/boxes/hashicorp-VAGRANTSLASH-bionic64/1.0.282/virtualbox/Vagrantfile>"]
DEBUG loader: Populating proc cache for #<Pathname:C:/Users/tankh/.vagrant.d/boxes/hashicorp-VAGRANTSLASH-bionic64/1.0.282/virtualbox/Vagrantfile>
DEBUG loader: Load procs for pathname: C:/Users/tankh/.vagrant.d/boxes/hashicorp-VAGRANTSLASH-bionic64/1.0.282/virtualbox/Vagrantfile
 INFO loader: Loading configuration in order: [:"1328588462240_hashicorp/bionic64_virtualbox", :home, :root, "1328592901400_machine_default"]
DEBUG loader: Loading from: 1328588462240_hashicorp/bionic64_virtualbox (evaluating)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Builder:0x0000026aad39fd90>
 INFO environment: Running hook: environment_load
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x0000026aad505450>
DEBUG checkpoint_client: starting plugin check
 INFO cli: CLI: [] "ssh" []
DEBUG checkpoint_client: plugin check complete
DEBUG cli: Invoking command class: VagrantPlugins::CommandSSH::Command []
DEBUG checkpoint_client: no information received from checkpoint
DEBUG command: Getting target VMs for command. Arguments:
DEBUG command:  -- names: []
DEBUG command:  -- options: {:single_target=>true}
DEBUG command: Loading all machines...
 INFO command: Active machine found with name default. Using provider: virtualbox
 INFO environment: Getting machine: default (virtualbox)
 INFO environment: Uncached load of machine.
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
DEBUG meta: Finding driver for VirtualBox version: 6.1.22
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_6_1
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
 INFO loader: Set "1328592901400_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "1328592901400_machine_default"]
ERROR loader: Unknown config sources: [:"1328588462240_hashicorp/bionic64_virtualbox"]
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO box_collection: Box found: hashicorp/bionic64 (virtualbox)
 INFO environment: Running hook: authenticate_box_url
 INFO runner: Running action: authenticate_box_url #<Vagrant::Action::Builder:0x0000026aad51ebf8>
 INFO warden: Calling IN action: #<VagrantPlugins::CloudCommand::AddAuthentication:0x0000026aad5c7190>
 WARN authenticate-box-url: Removing access token from URL parameter.
 WARN authenticate-box-url: Authentication token not added as GET parameter.
 INFO warden: Calling OUT action: #<VagrantPlugins::CloudCommand::AddAuthentication:0x0000026aad5c7190>
 INFO loader: Set :"1328588462240_hashicorp/bionic64_virtualbox" = ["#<Pathname:C:/Users/tankh/.vagrant.d/boxes/hashicorp-VAGRANTSLASH-bionic64/1.0.282/virtualbox/Vagrantfile>"]
 INFO loader: Loading configuration in order: [:"1328588462240_hashicorp/bionic64_virtualbox", :home, :root, "1328592901400_machine_default"]
DEBUG loader: Loading from: 1328588462240_hashicorp/bionic64_virtualbox (cache)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO machine: Initializing machine: default
 INFO machine:   - Provider: VagrantPlugins::ProviderVirtualBox::Provider
 INFO machine:   - Box: #<Vagrant::Box:0x0000026aad63a4d8>
 INFO machine:   - Data dir: c:/tmp/.vagrant/machines/default/virtualbox
DEBUG virtualbox: Instantiating the driver for machine ID: "4c952237-d778-4149-82c1-53829cd99eb0"
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
DEBUG meta: Finding driver for VirtualBox version: 6.1.22
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_6_1
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "4c952237-d778-4149-82c1-53829cd99eb0"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: Name:                        tmp_default_1623898626724_72295
Groups:                      /
Guest OS:                    Ubuntu (64-bit)
UUID:                        4c952237-d778-4149-82c1-53829cd99eb0
Config file:                 C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\tmp_default_1623898626724_72295.vbox
Snapshot folder:             C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\Snapshots
Log folder:                  C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\Logs
Hardware UUID:               4c952237-d778-4149-82c1-53829cd99eb0
Memory size:                 1024MB
Page Fusion:                 disabled
VRAM size:                   8MB
CPU exec cap:                100%
HPET:                        disabled
CPUProfile:                  host
Chipset:                     piix3
Firmware:                    BIOS
Number of CPUs:              1
PAE:                         enabled
Long Mode:                   enabled
Triple Fault Reset:          disabled
APIC:                        enabled
X2APIC:                      enabled
Nested VT-x/AMD-V:           disabled
CPUID Portability Level:     0
CPUID overrides:             None
Boot menu mode:              message and menu
Boot Device 1:               HardDisk
Boot Device 2:               DVD
Boot Device 3:               Not Assigned
Boot Device 4:               Not Assigned
ACPI:                        enabled
IOAPIC:                      enabled
BIOS APIC mode:              APIC
Time offset:                 0ms
RTC:                         UTC
Hardware Virtualization:     enabled
Nested Paging:               enabled
Large Pages:                 disabled
VT-x VPID:                   enabled
VT-x Unrestricted Exec.:     enabled
Paravirt. Provider:          Default
Effective Paravirt. Prov.:   KVM
State:                       running (since 2021-06-17T20:50:05.439000000)
Graphics Controller:         VBoxVGA
Monitor count:               1
3D Acceleration:             disabled
2D Video Acceleration:       disabled
Teleporter Enabled:          disabled
Teleporter Port:             0
Teleporter Address:
Teleporter Password:
Tracing Enabled:             disabled
Allow Tracing to Access VM:  disabled
Tracing Configuration:
Autostart Enabled:           disabled
Autostart Delay:             0
Default Frontend:
VM process priority:         default
Storage Controller Name (0):            IDE Controller
Storage Controller Type (0):            PIIX4
Storage Controller Instance Number (0): 0
Storage Controller Max Port Count (0):  2
Storage Controller Port Count (0):      2
Storage Controller Bootable (0):        on
Storage Controller Name (1):            SATA Controller
Storage Controller Type (1):            IntelAhci
Storage Controller Instance Number (1): 0
Storage Controller Max Port Count (1):  30
Storage Controller Port Count (1):      1
Storage Controller Bootable (1):        on
SATA Controller (0, 0): C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\ubuntu-18.04-amd64-disk001.vmdk (UUID: 1b213a31-724f-49db-809d-e965a31f3c59)
NIC 1:                       MAC: 080027BB1475, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)
NIC 1 Rule(0):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 2222, guest ip = , guest port = 22
NIC 2:                       disabled
NIC 3:                       disabled
NIC 4:                       disabled
NIC 5:                       disabled
NIC 6:                       disabled
NIC 7:                       disabled
NIC 8:                       disabled
Pointing Device:             PS/2 Mouse
Keyboard Device:             PS/2 Keyboard
UART 1:                      disabled
UART 2:                      disabled
UART 3:                      disabled
UART 4:                      disabled
LPT 1:                       disabled
LPT 2:                       disabled
Audio:                       disabled
Audio playback:              disabled
Audio capture:               disabled
Clipboard Mode:              disabled
Drag and drop Mode:          disabled
Session name:                headless
Video mode:                  800x600x32 at 0,0 enabled
VRDE:                        enabled (Address 127.0.0.1, Ports 5981, MultiConn: off, ReuseSingleConn: off, Authentication type: null)
Video redirection:           disabled
OHCI USB:                    disabled
EHCI USB:                    disabled
xHCI USB:                    disabled

USB Device Filters:

<none>

Available remote USB devices:

<none>

Currently Attached USB Devices:

<none>

Bandwidth groups:  <none>

Shared folders:

Name: 'vagrant', Host path: '\\?\C:\tmp' (machine mapping), writable

VRDE Connection:             not active
Clients so far:              0

Capturing:                   not active
Capture audio:               not active
Capture screens:             0
Capture file:                C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\tmp_default_1623898626724_72295.webm
Capture dimensions:          1024x768
Capture rate:                512kbps
Capture FPS:                 25kbps
Capture options:

Guest:

Configured memory balloon size: 0MB
OS type:                     Linux26_64
Additions run level:         2
Additions version:           6.0.10 r132072

Guest Facilities:

Facility "VirtualBox Base Driver": active/running (last update: 2021/06/17 20:50:20 UTC)
Facility "VirtualBox System Service": active/running (last update: 2021/06/17 20:50:25 UTC)
Facility "Seamless Mode": not active (last update: 2021/06/17 20:50:20 UTC)
Facility "Graphics Mode": not active (last update: 2021/06/17 20:50:20 UTC)


DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "4c952237-d778-4149-82c1-53829cd99eb0", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="tmp_default_1623898626724_72295"
groups="/"
ostype="Ubuntu (64-bit)"
UUID="4c952237-d778-4149-82c1-53829cd99eb0"
CfgFile="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.vbox"
SnapFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Snapshots"
LogFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Logs"
hardwareuuid="4c952237-d778-4149-82c1-53829cd99eb0"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="off"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="on"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="disk"
boot2="dvd"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="off"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2021-06-17T20:50:05.439000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="IDE Controller"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA Controller"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="1"
storagecontrollerbootable1="on"
"IDE Controller-0-0"="none"
"IDE Controller-0-1"="none"
"IDE Controller-1-0"="none"
"IDE Controller-1-1"="none"
"SATA Controller-0-0"="C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\ubuntu-18.04-amd64-disk001.vmdk"
"SATA Controller-ImageUUID-0-0"="1b213a31-724f-49db-809d-e965a31f3c59"
natnet1="nat"
macaddress1="080027BB1475"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,2222,,22"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="none"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="800,600,32"@0,0 1
vrde="on"
vrdeport=-1
vrdeports="5981"
vrdeaddress="127.0.0.1"
vrdeauthtype="null"
vrdemulticon="off"
vrdereusecon="off"
vrdevideochannel="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="vagrant"
SharedFolderPathMachineMapping1="\\\\?\\C:\\tmp"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="6.0.10 r132072"
GuestAdditionsFacility_VirtualBox Base Driver=50,1623963020625
GuestAdditionsFacility_VirtualBox System Service=50,1623963025691
GuestAdditionsFacility_Seamless Mode=0,1623963020667
GuestAdditionsFacility_Graphics Mode=0,1623963020617
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO interface: Machine: metadata ["provider", :virtualbox, {:target=>:default}]
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "4c952237-d778-4149-82c1-53829cd99eb0", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="tmp_default_1623898626724_72295"
groups="/"
ostype="Ubuntu (64-bit)"
UUID="4c952237-d778-4149-82c1-53829cd99eb0"
CfgFile="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.vbox"
SnapFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Snapshots"
LogFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Logs"
hardwareuuid="4c952237-d778-4149-82c1-53829cd99eb0"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="off"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="on"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="disk"
boot2="dvd"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="off"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2021-06-17T20:50:05.439000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="IDE Controller"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA Controller"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="1"
storagecontrollerbootable1="on"
"IDE Controller-0-0"="none"
"IDE Controller-0-1"="none"
"IDE Controller-1-0"="none"
"IDE Controller-1-1"="none"
"SATA Controller-0-0"="C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\ubuntu-18.04-amd64-disk001.vmdk"
"SATA Controller-ImageUUID-0-0"="1b213a31-724f-49db-809d-e965a31f3c59"
natnet1="nat"
macaddress1="080027BB1475"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,2222,,22"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="none"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="800,600,32"@0,0 1
vrde="on"
vrdeport=-1
vrdeports="5981"
vrdeaddress="127.0.0.1"
vrdeauthtype="null"
vrdemulticon="off"
vrdereusecon="off"
vrdevideochannel="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="vagrant"
SharedFolderPathMachineMapping1="\\\\?\\C:\\tmp"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="6.0.10 r132072"
GuestAdditionsFacility_VirtualBox Base Driver=50,1623963020625
GuestAdditionsFacility_VirtualBox System Service=50,1623963025691
GuestAdditionsFacility_Seamless Mode=0,1623963020667
GuestAdditionsFacility_Graphics Mode=0,1623963020617
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "4c952237-d778-4149-82c1-53829cd99eb0", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="tmp_default_1623898626724_72295"
groups="/"
ostype="Ubuntu (64-bit)"
UUID="4c952237-d778-4149-82c1-53829cd99eb0"
CfgFile="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.vbox"
SnapFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Snapshots"
LogFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Logs"
hardwareuuid="4c952237-d778-4149-82c1-53829cd99eb0"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="off"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="on"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="disk"
boot2="dvd"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="off"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2021-06-17T20:50:05.439000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="IDE Controller"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA Controller"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="1"
storagecontrollerbootable1="on"
"IDE Controller-0-0"="none"
"IDE Controller-0-1"="none"
"IDE Controller-1-0"="none"
"IDE Controller-1-1"="none"
"SATA Controller-0-0"="C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\ubuntu-18.04-amd64-disk001.vmdk"
"SATA Controller-ImageUUID-0-0"="1b213a31-724f-49db-809d-e965a31f3c59"
natnet1="nat"
macaddress1="080027BB1475"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,2222,,22"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="none"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="800,600,32"@0,0 1
vrde="on"
vrdeport=-1
vrdeports="5981"
vrdeaddress="127.0.0.1"
vrdeauthtype="null"
vrdemulticon="off"
vrdereusecon="off"
vrdevideochannel="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="vagrant"
SharedFolderPathMachineMapping1="\\\\?\\C:\\tmp"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="6.0.10 r132072"
GuestAdditionsFacility_VirtualBox Base Driver=50,1623963020625
GuestAdditionsFacility_VirtualBox System Service=50,1623963025691
GuestAdditionsFacility_Seamless Mode=0,1623963020667
GuestAdditionsFacility_Graphics Mode=0,1623963020617
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO command: With machine: default (#<VagrantPlugins::ProviderVirtualBox::Provider:0x0000026aad441208 @logger=#<Log4r::Logger:0x0000026aad441168 @fullname="vagrant::provider::virtualbox", @outputters=[], @additive=true, @name="virtualbox", @path="vagrant::provider", @parent=#<VagrantLogger:0x0000026aab89b648 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x0000026aac33b558 @mon_mutex=#<Thread::Mutex:0x0000026aac33b4e0>, @mon_mutex_owner_object_id=1328589429420, @mon_owner=nil, @mon_count=0, @name="stderr", @level=0, @formatter=#<Vagrant::Util::LoggingFormatter:0x0000026aac361140 @formatter=#<Log4r::BasicFormatter:0x0000026aac362400 @depth=7>>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x0000026aab89b530 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @machine=#<Vagrant::Machine: default (VagrantPlugins::ProviderVirtualBox::Provider)>, @driver=#<VagrantPlugins::ProviderVirtualBox::Driver::Meta:0x0000026aad48ee68 @logger=#<Log4r::Logger:0x0000026aad52fb10 @fullname="vagrant::provider::virtualbox::meta", @outputters=[], @additive=true, @name="meta", @path="vagrant::provider::virtualbox", @parent=#<Log4r::Logger:0x0000026aad441168 @fullname="vagrant::provider::virtualbox", @outputters=[], @additive=true, @name="virtualbox", @path="vagrant::provider", @parent=#<VagrantLogger:0x0000026aab89b648 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x0000026aac33b558 @mon_mutex=#<Thread::Mutex:0x0000026aac33b4e0>, @mon_mutex_owner_object_id=1328589429420, @mon_owner=nil, @mon_count=0, @name="stderr", @level=0, @formatter=#<Vagrant::Util::LoggingFormatter:0x0000026aac361140 @formatter=#<Log4r::BasicFormatter:0x0000026aac362400 @depth=7>>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x0000026aab89b530 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @level=1, @trace=false>, @interrupted=false, @vboxmanage_path="C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", @uuid="4c952237-d778-4149-82c1-53829cd99eb0", @driver=#<VagrantPlugins::ProviderVirtualBox::Driver::Version_6_1:0x0000026aad5679e8 @logger=#<Log4r::Logger:0x0000026aad682bc0 @fullname="vagrant::provider::virtualbox_6_1", @outputters=[], @additive=true, @name="virtualbox_6_1", @path="vagrant::provider", @parent=#<VagrantLogger:0x0000026aab89b648 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x0000026aac33b558 @mon_mutex=#<Thread::Mutex:0x0000026aac33b4e0>, @mon_mutex_owner_object_id=1328589429420, @mon_owner=nil, @mon_count=0, @name="stderr", @level=0, @formatter=#<Vagrant::Util::LoggingFormatter:0x0000026aac361140 @formatter=#<Log4r::BasicFormatter:0x0000026aac362400 @depth=7>>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x0000026aab89b530 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @interrupted=false, @vboxmanage_path="C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", @uuid="4c952237-d778-4149-82c1-53829cd99eb0">, @version="6.1.22">, @cap_logger=#<Log4r::Logger:0x0000026aac231608 @fullname="vagrant::capability_host::vagrantplugins::providervirtualbox::provider", @outputters=[], @additive=true, @name="provider", @path="vagrant::capability_host::vagrantplugins::providervirtualbox", @parent=#<VagrantLogger:0x0000026aab89b648 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x0000026aac33b558 @mon_mutex=#<Thread::Mutex:0x0000026aac33b4e0>, @mon_mutex_owner_object_id=1328589429420, @mon_owner=nil, @mon_count=0, @name="stderr", @level=0, @formatter=#<Vagrant::Util::LoggingFormatter:0x0000026aac361140 @formatter=#<Log4r::BasicFormatter:0x0000026aac362400 @depth=7>>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x0000026aab89b530 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @cap_host_chain=[[:virtualbox, #<#<Class:0x0000026aac233250>:0x0000026aac87a9b0>]], @cap_args=[#<Vagrant::Machine: default (VagrantPlugins::ProviderVirtualBox::Provider)>], @cap_caps={:docker=>#<Vagrant::Registry:0x0000026aac232738 @items={:public_address=>#<Proc:0x0000026aac883a10@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/docker/plugin.rb:60>, :proxy_machine=>#<Proc:0x0000026aac883920@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/docker/plugin.rb:65>, :has_communicator=>#<Proc:0x0000026aac883830@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/docker/plugin.rb:70>}, @results_cache={}>, :hyperv=>#<Vagrant::Registry:0x0000026aac2325f8 @items={:public_address=>#<Proc:0x0000026aab45e2b0@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/hyperv/plugin.rb:25>, :snapshot_list=>#<Proc:0x0000026aab45d888@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/hyperv/plugin.rb:30>, :configure_disks=>#<Proc:0x0000026aab45d680@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/hyperv/plugin.rb:35>, :cleanup_disks=>#<Proc:0x0000026aab474538@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/hyperv/plugin.rb:40>, :validate_disk_ext=>#<Proc:0x0000026aab4a6420@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/hyperv/plugin.rb:45>, :default_disk_exts=>#<Proc:0x0000026aab4a6010@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/hyperv/plugin.rb:50>, :set_default_disk_ext=>#<Proc:0x0000026aab4a5958@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/hyperv/plugin.rb:55>}, @results_cache={}>, :virtualbox=>#<Vagrant::Registry:0x0000026aac232530 @items={:forwarded_ports=>#<Proc:0x0000026aac891660@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/plugin.rb:27>, :nic_mac_addresses=>#<Proc:0x0000026aac891638@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/plugin.rb:32>, :public_address=>#<Proc:0x0000026aac891610@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/plugin.rb:37>, :configure_disks=>#<Proc:0x0000026aac8915e8@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/plugin.rb:42>, :cleanup_disks=>#<Proc:0x0000026aac8915c0@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/plugin.rb:47>, :validate_disk_ext=>#<Proc:0x0000026aac891598@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/plugin.rb:52>, :default_disk_exts=>#<Proc:0x0000026aac891570@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/plugin.rb:57>, :set_default_disk_ext=>#<Proc:0x0000026aac891548@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/plugin.rb:62>, :snapshot_list=>#<Proc:0x0000026aac891520@C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/plugin.rb:67>}, @results_cache={}>}>)
DEBUG command: Invoking `ssh` action on machine
 INFO machine: Calling action: ssh on provider VirtualBox (4c952237-d778-4149-82c1-53829cd99eb0)
 INFO interface: Machine: action ["ssh", "start", {:target=>:default}]
 INFO runner: Running action: machine_action_ssh #<Vagrant::Action::Builder:0x0000026aad5241e8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckVirtualbox:0x0000026aaca25c10>
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
DEBUG meta: Finding driver for VirtualBox version: 6.1.22
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_6_1
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "list", "hostonlyifs"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            3a0047f5-a39e-4a96-88f1-b98387310d51
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::b5b1:e035:7ba7:f087
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:0c
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "$(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: Get-WindowsOptionalFeature : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:3
+ $(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hyperviso ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WindowsOptionalFeature], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "$(Get-WindowsFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: Get-WindowsFeature : The term 'Get-WindowsFeature' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:3
+ $(Get-WindowsFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State
+   ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WindowsFeature:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckCreated:0x0000026aacad7a78>
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "4c952237-d778-4149-82c1-53829cd99eb0", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="tmp_default_1623898626724_72295"
groups="/"
ostype="Ubuntu (64-bit)"
UUID="4c952237-d778-4149-82c1-53829cd99eb0"
CfgFile="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.vbox"
SnapFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Snapshots"
LogFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Logs"
hardwareuuid="4c952237-d778-4149-82c1-53829cd99eb0"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="off"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="on"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="disk"
boot2="dvd"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="off"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2021-06-17T20:50:05.439000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="IDE Controller"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA Controller"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="1"
storagecontrollerbootable1="on"
"IDE Controller-0-0"="none"
"IDE Controller-0-1"="none"
"IDE Controller-1-0"="none"
"IDE Controller-1-1"="none"
"SATA Controller-0-0"="C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\ubuntu-18.04-amd64-disk001.vmdk"
"SATA Controller-ImageUUID-0-0"="1b213a31-724f-49db-809d-e965a31f3c59"
natnet1="nat"
macaddress1="080027BB1475"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,2222,,22"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="none"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="800,600,32"@0,0 1
vrde="on"
vrdeport=-1
vrdeports="5981"
vrdeaddress="127.0.0.1"
vrdeauthtype="null"
vrdemulticon="off"
vrdereusecon="off"
vrdevideochannel="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="vagrant"
SharedFolderPathMachineMapping1="\\\\?\\C:\\tmp"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="6.0.10 r132072"
GuestAdditionsFacility_VirtualBox Base Driver=50,1623963020625
GuestAdditionsFacility_VirtualBox System Service=50,1623963025691
GuestAdditionsFacility_Seamless Mode=0,1623963020667
GuestAdditionsFacility_Graphics Mode=0,1623963020617
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckAccessible:0x0000026aacad7988>
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "4c952237-d778-4149-82c1-53829cd99eb0", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="tmp_default_1623898626724_72295"
groups="/"
ostype="Ubuntu (64-bit)"
UUID="4c952237-d778-4149-82c1-53829cd99eb0"
CfgFile="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.vbox"
SnapFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Snapshots"
LogFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Logs"
hardwareuuid="4c952237-d778-4149-82c1-53829cd99eb0"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="off"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="on"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="disk"
boot2="dvd"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="off"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2021-06-17T20:50:05.439000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="IDE Controller"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA Controller"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="1"
storagecontrollerbootable1="on"
"IDE Controller-0-0"="none"
"IDE Controller-0-1"="none"
"IDE Controller-1-0"="none"
"IDE Controller-1-1"="none"
"SATA Controller-0-0"="C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\ubuntu-18.04-amd64-disk001.vmdk"
"SATA Controller-ImageUUID-0-0"="1b213a31-724f-49db-809d-e965a31f3c59"
natnet1="nat"
macaddress1="080027BB1475"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,2222,,22"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="none"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="800,600,32"@0,0 1
vrde="on"
vrdeport=-1
vrdeports="5981"
vrdeaddress="127.0.0.1"
vrdeauthtype="null"
vrdemulticon="off"
vrdereusecon="off"
vrdevideochannel="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="vagrant"
SharedFolderPathMachineMapping1="\\\\?\\C:\\tmp"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="6.0.10 r132072"
GuestAdditionsFacility_VirtualBox Base Driver=50,1623963020625
GuestAdditionsFacility_VirtualBox System Service=50,1623963025691
GuestAdditionsFacility_Seamless Mode=0,1623963020667
GuestAdditionsFacility_Graphics Mode=0,1623963020617
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckRunning:0x0000026aacad7938>
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "4c952237-d778-4149-82c1-53829cd99eb0", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="tmp_default_1623898626724_72295"
groups="/"
ostype="Ubuntu (64-bit)"
UUID="4c952237-d778-4149-82c1-53829cd99eb0"
CfgFile="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.vbox"
SnapFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Snapshots"
LogFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Logs"
hardwareuuid="4c952237-d778-4149-82c1-53829cd99eb0"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="off"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="on"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="disk"
boot2="dvd"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="off"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2021-06-17T20:50:05.439000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="IDE Controller"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA Controller"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="1"
storagecontrollerbootable1="on"
"IDE Controller-0-0"="none"
"IDE Controller-0-1"="none"
"IDE Controller-1-0"="none"
"IDE Controller-1-1"="none"
"SATA Controller-0-0"="C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\ubuntu-18.04-amd64-disk001.vmdk"
"SATA Controller-ImageUUID-0-0"="1b213a31-724f-49db-809d-e965a31f3c59"
natnet1="nat"
macaddress1="080027BB1475"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,2222,,22"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="none"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="800,600,32"@0,0 1
vrde="on"
vrdeport=-1
vrdeports="5981"
vrdeaddress="127.0.0.1"
vrdeauthtype="null"
vrdemulticon="off"
vrdereusecon="off"
vrdevideochannel="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="vagrant"
SharedFolderPathMachineMapping1="\\\\?\\C:\\tmp"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="6.0.10 r132072"
GuestAdditionsFacility_VirtualBox Base Driver=50,1623963020625
GuestAdditionsFacility_VirtualBox System Service=50,1623963025691
GuestAdditionsFacility_Seamless Mode=0,1623963020667
GuestAdditionsFacility_Graphics Mode=0,1623963020617
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SSHExec:0x0000026aacad7870>
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "4c952237-d778-4149-82c1-53829cd99eb0", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="tmp_default_1623898626724_72295"
groups="/"
ostype="Ubuntu (64-bit)"
UUID="4c952237-d778-4149-82c1-53829cd99eb0"
CfgFile="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.vbox"
SnapFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Snapshots"
LogFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Logs"
hardwareuuid="4c952237-d778-4149-82c1-53829cd99eb0"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="off"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="on"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="disk"
boot2="dvd"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="off"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2021-06-17T20:50:05.439000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="IDE Controller"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA Controller"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="1"
storagecontrollerbootable1="on"
"IDE Controller-0-0"="none"
"IDE Controller-0-1"="none"
"IDE Controller-1-0"="none"
"IDE Controller-1-1"="none"
"SATA Controller-0-0"="C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\ubuntu-18.04-amd64-disk001.vmdk"
"SATA Controller-ImageUUID-0-0"="1b213a31-724f-49db-809d-e965a31f3c59"
natnet1="nat"
macaddress1="080027BB1475"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,2222,,22"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="none"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="800,600,32"@0,0 1
vrde="on"
vrdeport=-1
vrdeports="5981"
vrdeaddress="127.0.0.1"
vrdeauthtype="null"
vrdemulticon="off"
vrdereusecon="off"
vrdevideochannel="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="vagrant"
SharedFolderPathMachineMapping1="\\\\?\\C:\\tmp"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="6.0.10 r132072"
GuestAdditionsFacility_VirtualBox Base Driver=50,1623963020625
GuestAdditionsFacility_VirtualBox System Service=50,1623963025691
GuestAdditionsFacility_Seamless Mode=0,1623963020667
GuestAdditionsFacility_Graphics Mode=0,1623963020617
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG virtualbox_6_1: Searching for SSH port: 22
DEBUG virtualbox_6_1: read_forward_ports: uuid=4c952237-d778-4149-82c1-53829cd99eb0 active_only=false
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "4c952237-d778-4149-82c1-53829cd99eb0", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="tmp_default_1623898626724_72295"
groups="/"
ostype="Ubuntu (64-bit)"
UUID="4c952237-d778-4149-82c1-53829cd99eb0"
CfgFile="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.vbox"
SnapFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Snapshots"
LogFldr="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\Logs"
hardwareuuid="4c952237-d778-4149-82c1-53829cd99eb0"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="off"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="on"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="disk"
boot2="dvd"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="off"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2021-06-17T20:50:05.439000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="IDE Controller"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA Controller"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="1"
storagecontrollerbootable1="on"
"IDE Controller-0-0"="none"
"IDE Controller-0-1"="none"
"IDE Controller-1-0"="none"
"IDE Controller-1-1"="none"
"SATA Controller-0-0"="C:\Users\tankh\VirtualBox VMs\tmp_default_1623898626724_72295\ubuntu-18.04-amd64-disk001.vmdk"
"SATA Controller-ImageUUID-0-0"="1b213a31-724f-49db-809d-e965a31f3c59"
natnet1="nat"
macaddress1="080027BB1475"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,2222,,22"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="none"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="800,600,32"@0,0 1
vrde="on"
vrdeport=-1
vrdeports="5981"
vrdeaddress="127.0.0.1"
vrdeauthtype="null"
vrdemulticon="off"
vrdereusecon="off"
vrdevideochannel="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="vagrant"
SharedFolderPathMachineMapping1="\\\\?\\C:\\tmp"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="C:\\Users\\tankh\\VirtualBox VMs\\tmp_default_1623898626724_72295\\tmp_default_1623898626724_72295.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="6.0.10 r132072"
GuestAdditionsFacility_VirtualBox Base Driver=50,1623963020625
GuestAdditionsFacility_VirtualBox System Service=50,1623963025691
GuestAdditionsFacility_Seamless Mode=0,1623963020667
GuestAdditionsFacility_Graphics Mode=0,1623963020617
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
DEBUG virtualbox_6_1:   - [1, "ssh", 2222, 22, "127.0.0.1"]
 INFO subprocess: Starting process: ["C:\\Program Files\\Git\\usr\\bin/ssh.EXE"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-J [user@]host[:port]] [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port] [-Q query_option] [-R address]
           [-S ctl_path] [-W host:port] [-w local_tun[:remote_tun]]
           [user@]hostname [command]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 255
 INFO ssh: Invoking SSH: C:\Program Files\Git\usr\bin/ssh.EXE ["vagrant@127.0.0.1", "-p", "2222", "-o", "LogLevel=FATAL", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "IdentitiesOnly=yes", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-i", "c:/tmp/.vagrant/machines/default/virtualbox/private_key"]
DEBUG safe_exec: Converting command and arguments to common UTF-8 encoding for exec.
DEBUG safe_exec: Command: `"C:\\Program Files\\Git\\usr\\bin/ssh.EXE"` Args: `["vagrant@127.0.0.1", "-p", "2222", "-o", "LogLevel=FATAL", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "IdentitiesOnly=yes", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-i", "c:/tmp/.vagrant/machines/default/virtualbox/private_key"]`
DEBUG safe_exec: Converted - Command: `"C:\\Program Files\\Git\\usr\\bin/ssh.EXE"` Args: `["vagrant@127.0.0.1", "-p", "2222", "-o", "LogLevel=FATAL", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "IdentitiesOnly=yes", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-i", "c:/tmp/.vagrant/machines/default/virtualbox/private_key"]`
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Jun 17 20:55:07 UTC 2021

  System load:  0.03              Processes:           92
  Usage of /:   2.5% of 61.80GB   Users logged in:     0
  Memory usage: 11%               IP address for eth0: 10.0.2.15
  Swap usage:   0%

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

0 packages can be updated.
0 updates are security updates.


Last login: Thu Jun 17 02:59:03 2021 from 10.0.2.2
vagrant@vagrant:~$ pwd
/home/vagrant
vagrant@vagrant:~$ exit
logout
Connection to 127.0.0.1 closed.

c:\tmp>cd d:\projects\github\khtan-private

c:\tmp>ls
Vagrantfile  announce.txt  announce1.txt  init.el  ubuntu-installed.org

c:\tmp>d:

d:\projects\github\khtan-private>
d:\projects\github\khtan-private>git clone https://github.com/khtan-private/docker4.net.git
Cloning into 'docker4.net'...
remote: Enumerating objects: 1291, done.
remote: Counting objects: 100% (1291/1291), done.
remote: Compressing objects: 100% (844/844), done.
remote: Total 1291 (delta 556), reused 1087 (delta 359), pack-reused 0
Receiving objects: 100% (1291/1291), 17.37 MiB | 402.00 KiB/s, done.
Resolving deltas: 100% (556/556), done.

d:\projects\github\khtan-private>ls
docker4.net  rust  webapi

d:\projects\github\khtan-private>cd docker4.net

d:\projects\github\khtan-private\docker4.net>ls
README.md  app  docker  docs  lessons  src  vagrant

d:\projects\github\khtan-private\docker4.net>cd vagrant/05

d:\projects\github\khtan-private\docker4.net\vagrant\05>ls
Vagrantfile  pull-images.ps1  pull-images.sh  setup.ps1  setup.sh

d:\projects\github\khtan-private\docker4.net\vagrant\05>vagrant up
Bringing machine 'manager' up with 'virtualbox' provider...
Bringing machine 'worker' up with 'virtualbox' provider...
Bringing machine 'worker2' up with 'virtualbox' provider...
Bringing machine 'winworker' up with 'virtualbox' provider...
==> manager: Box 'bento/ubuntu-20.04' could not be found. Attempting to find and install...
    manager: Box Provider: virtualbox
    manager: Box Version: >= 0
==> manager: Loading metadata for box 'bento/ubuntu-20.04'
    manager: URL: https://vagrantcloud.com/bento/ubuntu-20.04
==> manager: Adding box 'bento/ubuntu-20.04' (v202105.25.0) for provider: virtualbox
    manager: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-20.04/versions/202105.25.0/providers/virtualbox.box
    manager:
==> manager: Successfully added box 'bento/ubuntu-20.04' (v202105.25.0) for 'virtualbox'!
==> manager: Importing base box 'bento/ubuntu-20.04'...
==> manager: Matching MAC address for NAT networking...
==> manager: Checking if box 'bento/ubuntu-20.04' version '202105.25.0' is up to date...
==> manager: Setting the name of the VM: manager
==> manager: Fixed port collision for 22 => 2222. Now on port 2200.
==> manager: Clearing any previously set network interfaces...
==> manager: Preparing network interfaces based on configuration...
    manager: Adapter 1: nat
    manager: Adapter 2: hostonly
==> manager: Forwarding ports...
    manager: 22 (guest) => 2200 (host) (adapter 1)
==> manager: Running 'pre-boot' VM customizations...
==> manager: Booting VM...
==> manager: Waiting for machine to boot. This may take a few minutes...
    manager: SSH address: 127.0.0.1:2200
    manager: SSH username: vagrant
    manager: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

** Initialize the Swarm

Swarm mode is a feature of the Docker Engine so you don't need to install any additional software.

_Connect to the manager VM and initialize the cluster:_

```
cd "$env:docker4dotnet/vagrant/05"

vagrant status

vagrant ssh manager

docker swarm init
```

docker swarm join --token SWMTKN-1-465ztyegx85cx8i1gzsipo53m2xnzw000jej568n80bszl1u2o-1nek61xpib3pz11ip8gt6tznz 172.24.242.1:2377
worker: 172.24.241.14

> You now have a functional single-node Swarm. The output shows the command you run on other nodes to join the Swarm. 

_You can manage the other nodes from the manager:_

```
docker node ls

docker swarm join-token manager

docker swarm join-token worker

exit
```

** Join a Linux worker node

The manager runs the orchestration components. You add worker nodes to run your application containers. 

_Add a Linux worker node:_

```
vagrant ssh worker

ip a

# docker swarm join [join-token] --advertise-addr [ip address]
```
docker swarm join --token SWMTKN-1-465ztyegx85cx8i1gzsipo53m2xnzw000jej568n80bszl1u2o-1nek61xpib3pz11ip8gt6tznz 172.24.242.1:2377 --advertise-addr 172.24.241.14

> Docker can work out the machine's IP address, but you should specify it if you have multiple addresses.

_Check the Docker Engine status:_

```
docker info

exit
```
https://forums.docker.com/t/docker-worker-nodes-shown-as-down-after-re-start/22329

** Join a Windows worker node

Docker Swarm works in the same way on Windows and Linux. You use the same join command, and Windows nodes can be managers or workers.

_Join the Windows node:_

```
# password :vagrant
vagrant ssh winworker

ipconfig

# docker swarm join [join-token] --advertise-addr [ip address]
```
winworker: 172.24.248.7
docker swarm join --token SWMTKN-1-465ztyegx85cx8i1gzsipo53m2xnzw000jej568n80bszl1u2o-1nek61xpib3pz11ip8gt6tznz 172.24.242.1:2377 --advertise-addr 172.24.248.7

docker swarm join --token SWMTKN-1-5aj27guhefwi8cyfd2hkl7pbp02n5uhbcql2b4qtmvxezvchtw-a6czm7dtbgbwlykbe9g7wtc0x 172.22.53.218:2377 --advertise-addr 172.22.57.109

** Run a simple app

Worker nodes just run your workloads, they're assigned work by the manager. You run `docker` commands on the manager and typically leave the workers alone.

_Check the Swarm setup:_

```
vagrant ssh manager

docker node ls

docker node inspect worker

docker node inspect winworker
```

You run apps in Swarm Mode as **services**, using the same compute abstraction as Compose. A service can run in one or more containers on any nodes.

_Deploy a basic web app:_

```
docker service create --name whoami -p 8080:80 docker4dotnet/whoami

docker service ps whoami

docker node inspect worker -f '{{.Status.Addr}}'

docker node inspect manager -f '{{.Status.Addr}}'
```

Bug: winworker shows it is running on linux

> There's a single container running the service, but you can browse to port `8080` on any node and the traffic gets routed to the container.

Scale up and more containers will be created. Publishing a port in Swarm mode uses the ingress network, so incoming requests get load-balanced between containers. 

_Update the service to scale up:_

```
docker service update --replicas 10 whoami

docker service ps whoami

url="$(docker node inspect winworker -f '{{.Status.Addr}}'):8080"

echo $url

curl $url
```

worker: 172.22.51.3
manager: 172.22.53.218
winworker: 172.22.57.109

> This is a multi-architecture .NET Core image, so it can run on Windows or Linux. Repeat the curl command to see different OS responses.

_Check the logs and clear up:_

```
docker service logs whoami

docker service rm whoami

docker ps
```

Services are first-class citizens which you administer on the manager node. Swarm mode enables extra features in the Docker CLI, but you can only use them on the manager - typically you'd set up a remote connection.

** Modelling apps for Docker Swarm 

Now we have a cluster running and we've seen how services are created and deployed as containers on the nodes. 

Next we'll see how the Docker Compose format supports Swarm mode. You can model your applications to deploy them to the cluster and take full advantage of the orchestration features.

** ?Missing lecture material : how to shut/restart vagrant and docker swarm
At the close of the lecture, everything is left running. It would be useful for students to learn
how to shut down docker swarm, then vagrant in preparation for another session.
For example, I had to restart my PC because there were some updates going on. 

*** transcript of vagrant destroy
**** PS C:\cprojects\github\khtan-private\docker4.net\vagrant\05> vagrant status
 Current machine states:

 manager                   off (hyperv)
 worker                    off (hyperv)
 worker2                   off (hyperv)
 winworker                 off (hyperv)

 This environment represents multiple VMs. The VMs are all listed
 above with their current state. For more information about a specific
 VM, run `vagrant status NAME`.
****  PS C:\cprojects\github\khtan-private\docker4.net\vagrant\05> vagrant destroy
     winworker: Are you sure you want to destroy the 'winworker' VM? [y/N] Y
 ==> winworker: Stopping the machine...
 ==> winworker: Deleting the machine...
     worker2: Are you sure you want to destroy the 'worker2' VM? [y/N] y
 ==> worker2: Stopping the machine...
 ==> worker2: Deleting the machine...

 Vagrant requires administrator access for pruning SMB shares and
 may request access to complete removal of stale shares.
     worker: Are you sure you want to destroy the 'worker' VM? [y/N] y
 ==> worker: Stopping the machine...
 ==> worker: Deleting the machine...

 Vagrant requires administrator access for pruning SMB shares and
 may request access to complete removal of stale shares.
     manager: Are you sure you want to destroy the 'manager' VM? [y/N] y
 ==> manager: Stopping the machine...
 ==> manager: Deleting the machine...

 Vagrant requires administrator access for pruning SMB shares and
 may request access to complete removal of stale shares.
